# Set the base image to nodejs:5.1.0
FROM nodejs:5.1.0

# File Author / Maintainer
MAINTAINER Thanassis Zografos <tzografos@gmail.com>

WORKDIR /data/modules/analytics2

RUN git clone https://github.com/kabitakis/github-analytics.git

RUN npm install nodemon -g

ADD run.sh run.sh

WORKDIR /data/modules/analytics2/github-analytics/

ADD run.sh run.sh

CMD ["./run.sh"]

#END OF DOCKER FILE



# CONTENTS OF run.sh
#!/bin/bash

npm install

./node_modules/.bin/browserify -t reactify public/*.js -o public/js/bundle.js

GHTOKEN='xxxxxxxxxxxx' npm run dev
